name: Deploy Java App to SAP BTP

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Install Cloud Foundry CLI
        run: |
          CF_CLI_URL=$(curl -s https://api.github.com/repos/cloudfoundry/cli/releases/latest \
            | grep "browser_download_url" \
            | grep "linux_x86-64.tgz" \
            | cut -d '"' -f 4)

          echo "Downloading CF CLI from: $CF_CLI_URL"
          curl -LO "$CF_CLI_URL"

          FILE_NAME=$(basename "$CF_CLI_URL")
          tar -xvzf "$FILE_NAME"

          # Use sudo to force-remove the existing dangling symlink or file
          sudo rm -f /usr/local/bin/cf

          # Move the new binary and set executable permission
          sudo mv cf /usr/local/bin/cf
          sudo chmod +x /usr/local/bin/cf

          # Verify installation
          cf version

      - name: Deploy to SAP BTP
        env:
          CF_API: ${{ secrets.CF_API }}
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
        run: |
          cf api $CF_API
          cf auth $CF_USERNAME $CF_PASSWORD
          cf target -o $CF_ORG -s $CF_SPACE
          cf push